[workspace]
name = "rfdetr-train"
version = "0.1.0"
channels = ["conda-forge"]
platforms = ["win-64"]

[dependencies]
python = "3.10.*"
pyyaml = "*"
opencv = "*"
tqdm = "*"
matplotlib = "*"
scipy = "*"
numpy = "*"
einops = "*"
pycocotools = "*"
pillow = "*"

[pypi-dependencies]
torch = "*"
torchvision = "*"

[pypi-options]
extra-index-urls = ["https://download.pytorch.org/whl/cu121"]
